<a href="https://colab.research.google.com/github/jimin18/jimin/blob/master/0331hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Man:
  def __init__(self,name):
    self.name=name
    print("Initialized!")

  def hello(self):
    print("Hello "+ self.name + "!")

  def goodbye(self):
    print("Good-bye " + self.name + "!")

m= Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


In [ ]:
import numpy as np

In [ ]:
x= np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [ ]:
x= np.array([1.0, 2.0,3.0])
y= np.array([2.0, 4.0,6.0])
x+y
x/2.0

array([0.5, 1. , 1.5])

In [ ]:
A=np.array([[1,2], [3,4]])
print(A)
A.shape
A.dtype

B=np.array([[3,0],[0,6]])

A+B
A*B

print(A)
A*10

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


array([[10, 20],
       [30, 40]])

In [ ]:
A=np.array([[1,2], [3,4]])
B=np.array([10,20])
A*B

array([[10, 40],
       [30, 80]])

In [ ]:
X=np.array([[51,55],[14,19],[0,4]])
print(X)
X[0]
X[0][1]

for row in X:
  print(row)

X= X.flatten()
print(X)

X[np.array([0,2,4])]

X > 15
X[X>15]

[[51 55]
 [14 19]
 [ 0  4]]
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]


array([51, 55, 19])